version: "3.2"
services:
  riemann:
    image: rlister/riemann
    container_name: riemann
    environment:
      - GRAPHITE_HOST=graphite
    volumes:
      - './riemann:/app/etc'
    expose:
      - '5555'
    links:
      - graphite:graphite
    networks:
      - monitoring

  graphite:
    image: sitespeedio/graphite
    container_name: graphite
    # Internal Network, skip password
    # volumes:
    #   - './graphite/nginx/.htpasswd:/etc/nginx/.htpasswd'
    expose:
      - '80'
      - '2003'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:6.2.0
    container_name: grafana
    links:
      - 'graphite:graphite'
    # Chinese version, but only some parts are finished.
    # volumes:
    #   - './grafana/public:/usr/share/grafana/public'
    ports:
      - '8000:3000'
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

