version: '3.3'
services:
  portal:
    image: registry.cn-shanghai.aliyuncs.com/pgx-docker-registry/nginx-auth:base
    container_name: ${INSTANCE}-portal
    restart: always
    env_file: 
      - ../custom/env/auth/.env
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      AUTH_MODE: ${AUTH_MODE}
      INTROSPEC_ENDPOINT: ${INTROSPEC_ENDPOINT}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    networks:
      - clinico-omics-network
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ${WORKDIR}/clinico-omics/attachments:/data/clinico-omics/attachments
      - ${WORKSPACE}/nginx:/conf/nginx
      - ${WORKSPACE}/resty/http.lua:/usr/local/openresty/lualib/resty/http.lua
      - ${WORKSPACE}/resty/http_headers.lua:/usr/local/openresty/lualib/resty/http_headers.lua
      - ${WORKSPACE}/resty/openidc.lua:/usr/local/openresty/lualib/resty/openidc.lua

  mysql:
    image: mysql:5.7.32
    container_name: mysql
    expose: 
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - clinico-omics-network
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${WORKSPACE}/db/data:/var/lib/mysql
    healthcheck:
     test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"

  keycloak:
    image: jboss/keycloak:11.0.3
    container_name: keycloak
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDR}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JDBC_PARAMS: ${JDBC_PARAMS}
    depends_on:
      - mysql
    expose: 
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - clinico-omics-network
    healthcheck:
     test: "curl -f http://localhost:8080/auth || exit 1"
     
networks:
  clinico-omics-network:
    external:
      name: clinico-omics-network
